zuul:
  routes:
    foos:
      path: /foos/**
      url: http://localhost:8080/spring_war_exploded/greeting

## 关闭使用eureka负载路由
#ribbon:
#  eureka:
#    enabled: false

# 如果不使用eureka的话，需要自己定义路由的那个服务的其他负载服务
#spring-demo:
#  ribbon:
#    # 这里写你要路由的demo服务的所有负载服务请求地址，本项目只启动一个，因此只写一个
#    listOfServers: http://localhost:8080/spring_war_exploded/greeting
